### ISSUE TITLE
update please

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-docker#1]
While I did not use the docker option for https://github.com/OlegKunitsyn/gnucobol-debug myself it looks like a useful thing at least for "first-timers" that aren't familiar with COBOL and/or GnuCOBOL and want to give it a try.
The current nightly has an important fix for `-fdump=RW` (which is part of `-fdump=ALL`) and as this is a useful option to use with the debugger I suggest to update.

**Comment by OlegKunitsyn** [comment]
The goal was to reduce the number of controlled environments. With the image we (you) can deliver the latest version to the users without months (and years) of awaiting the distributions. We cut the 
corners for productivity.

The archive timestamped 26 Mai 2020 17∶43∶19 CEST. The Docker image is already the latest one, I see no changes.

I kindly ask you to take a look at the warnings and failed tests during the build of the image. I've commented Dockerfile for you.

**Comment by GitMensch** [comment]
Sorry for the confusion. I do also think that one environment is good (currently 3.x branch snapshots, as soon as 3.1rc1 is out we should use that) is good.

I obviously was confused myself as I've not merged the commit I've referenced, just did this some minutes ago (the creation of the nightly build tarball likely needs some time), I suggest to just apply the changes from [GnuCOBOL rev 3585](https://sourceforge.net/p/open-cobol/code/3585/) and update the dockerfile.
