### ISSUE TITLE
update to GC 3.1.1

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-docker#2]
release found at https://ftpmirror.gnu.org/gnucobol

**Comment by noleakseu** [comment]
`docker pull olegkunitsyn/gnucobol:3.1`

**Comment by OlegKunitsyn** [comment]
`docker pull olegkunitsyn/gnucobol:3.1`

**Comment by GitMensch** [comment]
Hm, the code in this repo is older than 3.1.1 from last days. Is this repo obsolete or just not updated?

**Comment by OlegKunitsyn** [comment]
The master has been updated. Thank you for the reminder.

**Comment by GitMensch** [comment]
GnuCOBOL's announcement of 3.1 was with 3.1.2 - you likely want to update...

**Comment by OlegKunitsyn** [comment]
Thanks for info! 2 of 3 my libs fail on GC 3.1.

I guess 'out of bounds' is a permanent false negative effect using `any length`.
```
# https://gitlab.com/OlegKunitsyn/core-network
src/string.cbl:368: error: length of 'l-csv' out of bounds: 2

# https://github.com/OlegKunitsyn/core-string
In file included from /tmp/cob1_1.c:1387:
/tmp/cob1_1.c.l5.h: In function 'receive__udp_':
/tmp/cob1_1.c.l5.h:20:1: error: unknown type name 'cob_decimal'
   20 | cob_decimal *d0 = NULL;
      | ^~~~~~~~~~~
/tmp/cob1_1.c:1742:5: warning: implicit declaration of function 'cob_decimal_set_llint'; did you mean 'cob_decimal_alloc'? [-Wimplicit-function-declaration]
 1742 |     cob_decimal_set_llint (d0, (cob_s64_t)b_139);
      |     ^~~~~~~~~~~~~~~~~~~~~
      |     cob_decimal_alloc
/tmp/cob1_1.c:1743:5: warning: implicit declaration of function 'cob_decimal_get_field' [-Wimplicit-function-declaration]
 1743 |     cob_decimal_get_field (d0, &f_158, 0);
      |     ^~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/cob1_1.c:2203:
/tmp/cob1_1.c.l7.h: In function 'receive__tcp_':
/tmp/cob1_1.c.l7.h:20:1: error: unknown type name 'cob_decimal'
   20 | cob_decimal *d0 = NULL;
      | ^~~~~~~~~~~
```

**Comment by GitMensch** [comment]
I can't comment on the first one as the source are not accessible without login via that URL. The second one should be fine if you either compile with an old version of cobc and have an old libcob.h installed or use a current version of libcob.h with a current version of cobc. It _looks_ like you have an old cobc with a new libcob.h. Can you please check and provide sources and command line for compilation of both, together with the version of cobc you use?

**Comment by GitMensch** [comment]
@OlegKunitsyn can you please recheck? We may need to report a bug on GnuCOBOL for your cases as the planning for 3.2 should have most bug reports included - but that's only possible when we know about actual issues - in theory both of your test cases should work...

**Comment by OlegKunitsyn** [comment]
I've fixed both. For example, `cob_decimal` issue
```
-    compute ws-buffer-length = RETURN-CODE.
+    move RETURN-CODE to ws-buffer-length.
```

**Comment by GitMensch** [comment]
Hm, that's a workaround which does not solve the original issue (which _looks_ like either old cobc with new libcob.h or a bug in cobc which should be fixed then (I could not found a failing sample yet - can you please provide yours?)

I'd also like to know more about the any length issue you've seen, can you change https://gitlab.com/OlegKunitsyn/core-network to be a public repository?

**Comment by OlegKunitsyn** [comment]
The "out of bounds" issue fixed this way:
```
-     when l-csv(ws-csv-pointer:2) = ", "
+     when l-csv(ws-csv-pointer:1) = "," and l-csv(1 + ws-csv-pointer:1) = " "
```
I guess both were my bad, 3.1 compiler might be more sensitive than 2.2.

**Comment by GitMensch** [comment]
> I guess both were my bad, 3.1 compiler might be more sensitive than 2.2.

I don't think so. The second one is definitely a bug - I've created [#704 3.1 regression: ANY LENGTH cannot have ref-mod, POS not context-sensitive](https://sourceforge.net/p/gnucobol/bugs/704/) for that, expect it to be fixed "soon" and shipped with 3.2 (targeted for March 2021).

Can you please provide a complete example of the cob_decimal problem? A C compiler error is nearly always (with the exception of "direct C CALLs") a bug. Thank you.

**Comment by OlegKunitsyn** [comment]
```
identification division.
program-id. receive-udp.
environment division.
configuration section.
repository. function trim length intrinsic.
data division.
working-storage section.
    78 AF_INET value 2.
    78 SOCK_DGRAM value 2.
    78 SIGINT value 2.
    01 SOL_SOCKET usage binary-int value 1.
    01 SO_REUSEADDR usage binary-int value 2.
    01 YES usage binary-int value 1.
    01 ws-address.
        05 server-family usage binary-short.
        05 server-port usage binary-short unsigned.
        05 server-ip-address usage binary-int.
        05 filler pic x(8) value low-values.
    01 ws-udp-socket usage binary-int external.
    01 ws-buffer pic x(1024).
    01 ws-buffer-length usage binary-short unsigned.
    01 ws-error pic x(64).
    01 ws-signal-handler usage program-pointer.
linkage section.
    01 l-host pic x any length.
    01 l-port usage binary-short unsigned.
    01 l-limit usage binary-short unsigned.
    01 l-callback usage program-pointer.
procedure division using l-host, l-port, l-limit, l-callback.
server-start section.
    set ws-signal-handler to entry "server-stop".
    call "signal" using by value SIGINT by value ws-signal-handler.

    call "socket" using
        by value AF_INET
        by value SOCK_DGRAM
        by value 0
        giving ws-udp-socket
    end-call.
    if RETURN-CODE = -1
        move "socket failed" to ws-error
        perform server-error
    end-if.

    call "setsockopt" using
        by value ws-udp-socket
        by value SOL_SOCKET
        by value SO_REUSEADDR
        by reference YES
        by value length(YES)
    end-call. 
    if RETURN-CODE = -1
        move "setsockopt failed" to ws-error
        perform server-error
    end-if.

    call "htons" using by value l-port giving server-port.

    move AF_INET to server-family.
    
    if l-host = "localhost" or "INADDR_ANY"
        move 0 to server-ip-address
    else
        call "inet_addr" using by reference l-host giving server-ip-address end-call
    end-if.

    call "bind" using
        by value ws-udp-socket
        by reference ws-address
        by value length(ws-address)
    end-call.
    if RETURN-CODE = -1
        move "bind failed" to ws-error
        perform server-error
    end-if.

    display "UDP server started on " l-host ":" l-port ". Hit Ctrl+C to stop.".

    perform until exit
        move SPACES to ws-buffer
        call "recv" using
            by value ws-udp-socket
            by reference ws-buffer
            by value length(ws-buffer)
            by value 0
        end-call
        if RETURN-CODE = -1
            move "recv failed" to ws-error
            perform server-error
        end-if
        
        compute ws-buffer-length = RETURN-CODE
        if ws-buffer-length = 0
            move SPACE to ws-buffer
            move 1 to ws-buffer-length
        end-if

        call l-callback using ws-buffer, ws-buffer-length on exception 
           display "Error occurred calling message-handler" upon syserr
        end-call

        if l-limit > 0
           subtract 1 from l-limit
           if l-limit = 0
               exit perform
           end-if
        end-if
    end-perform.
    call ws-signal-handler using by value SIGINT.
    goback.
server-error section.
    if ws-udp-socket <> 0
       display "Error: " ws-error upon syserr
    end-if.
    goback.
identification division.
program-id. server-stop.
data division.
working-storage section.
    01 ws-udp-socket usage binary-int external.
linkage section.
    01 l-signal usage binary-long.
procedure division using l-signal returning omitted.
    display SPACE.
    call "close" using by value ws-udp-socket.
    display "UDP server stopped.".
    move 0 to ws-udp-socket.
    goback.
end program server-stop.
end program receive-udp.

```

**Comment by GitMensch** [comment]
Hm, I've compiled that with 2.2.0 and 3.1.2 using `cobc -free -g -v` (also leaving both later options out) and both compiled fine :-/

**Comment by OlegKunitsyn** [comment]
Then it was my fault somewhere else. Nevermind.

**Comment by OlegKunitsyn** [comment]
VS Code has API for visualization of tests. Only problem is inability to determine which assertion failed/passed without instrumentation. Is it possible to implement `MODULE-CALLER-LINE`, `MODULE-CALLER-PATH` and `MODULE-CALLER-SOURCE` functions in upcoming versions of GC?

**Comment by GitMensch** [comment]
Hi Oleg, seems I've missed something here. What are those functions you write about?

Maybe the following is very much what you need?

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. dumpcall.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 STDERR   USAGE POINTER.

       PROCEDURE DIVISION.
           CALL "CBL_GC_HOSTED"   USING STDERR "stderr"
           CALL "cob_stack_trace" USING BY VALUE STDERR
                                  RETURNING NOTHING
           GOBACK.
```

This uses the 3.1+ available external C-ABI function `cob_stack_trace` which gets any `FILE *` (and for ease uses `CBL_GC_HOSTED` which provides access to both stderr and stdout). Of course you can use that from any COBOL program or from "C" and pass it any `FILE *`.
To be actually useful you'd likely need to compile the COBOL sources with `-fsource-location` (which is implied by both `-g` and `--debug`).

**Comment by OlegKunitsyn** [comment]
A workaround which requires additional parsing of the stack trace... No, thanks :)

**Comment by GitMensch** [comment]
If you explicit specify *what* you need and which result you'd expect then I would have the option to investigate.

**Comment by OlegKunitsyn** [comment]
Required:
`MODULE-CALLER-LINE` Returns the line number of the calling program

Nice to have:
`MODULE-CALLER-PATH` Returns the source code path of the calling program used when compiling module.
`MODULE-CALLER-SOURCE` Returns the source file of the calling program used when compiling module.
