### ISSUE TITLE
Outdated code

### ISSUE THREAD

**Issue by Smitty2018** [OlegKunitsyn/gnucobol-docker#4]
I've found https://github.com/OCamlPro/gnucobol/tree/gnucobol-3.x (also has a tag for last 3.2 preview), wouldn't it be reasonable to move to this place for the docker source?

**Comment by OlegKunitsyn** [comment]
You can any image including olegkunitsyn/gnucobol:3.2-dev
ATM the latest sources are building with errors:
ERROR: 1178 tests were run,
36 failed (31 expected failures).
7 tests were skipped.

**Comment by GitMensch** [comment]
> ATM the latest sources are building with errors:

This is now interesting for me. Can you please provide tests/testsuite.log to the [gnucobol bug mailing](https://savannah.gnu.org/mail/?group=gnucobol) or via mail to me (see Changelog files) or issue tracker https://sourceforge.net/p/gnucobol/bugs/ ?
We didn't have a single failing build reported with the 3.2 preview so far, and obviously I'd like to get rid of those before the release candidate.
